### ISSUE TITLE
Using the tikz argument 'scale' results in unexpected behaviour

### ISSUE THREAD

**Issue by ErinvanderVeen** [nichtich/tkz-orm#3]
When using the tikz 'scale'-argument, uniqueness constraints are no longer aligned with their role. As if they are not affected by the argument.

**Comment by nichtich** [comment]
Could you give an example? Which version do you use (0.1.2 or the current from master branch)?

**Comment by camilstaps** [comment]
You're probably using simply `scale=2`, while you need to [transform the shape](http://tex.stackexchange.com/a/26852/23992) as well: `scale=2,transform shape`. This works at least for the employee example.

Another option is to [transform the canvas](http://tex.stackexchange.com/a/26847/23992), or to [use a resizebox](http://tex.stackexchange.com/a/4340/23992).

All these options scale the text as well though. Could you confirm that this is what you're looking for?

**Comment by ErinvanderVeen** [comment]
This is exactly what I was looking for. Thanks for the help.

Edit:
I would like to retract my previous statement.

```
\begin{tikzpicture}
 \binary[unique=1] (r) {};
\end{tikzpicture}
```

Here the uniqueness constraint is aligned properly.

```
\begin{tikzpicture}[scale=5]
 \binary[unique=1] (r) {};
\end{tikzpicture}
```

Here it is misaligned.

I'm using the current from the master branch.
