### ISSUE TITLE
Uniqueness constraint on vroles

### ISSUE THREAD

**Issue by camilstaps** [nichtich/tkz-orm#7]
It seems uniqueness constraints on `\vroles` aren't rotated properly.

A MWE is as simple as `\vroles[unique=2]`. The uniqueness bar is misplaced, horizontal and too short.

**Comment by camilstaps** [comment]
I believe this is an issue in `\pgfdeclareshape{uniqueness bar}`. It _might_ be that we have to query the current transformation matrix as was necessary to fix #3.

`\vroles` is just `\roles` with a 90 degree rotation. It would be nice to fix this generically for any rotation.

(I currently don't have time to look into this but wanted to report it anyway to show that it is a known issue. And perhaps I can get back to this at some point...)

**Comment by camilstaps** [comment]
Also `xshift` and `yshift` seem swapped for vertical roles, although that is something that cannot be solved by `tkz-orm` (it is because of `rectangle split`).

**Comment by nicolaiskogheim** [comment]
Is there a workaround one can use for now?

I tried `\draw`ing a line where the bar should've been, but I'm very new to Latex and tikz and cannot get it to look right.

So far I've got this:

``` tex
    \vbinary (d) {} ;
    \draw[uniqueness bar, xshift=2cm] (d.south east) -- (d.three south) ;
```

![Screenshot of vrole with poor uniqueness bar](https://www.dropbox.com/s/uoly0l6x5nkwt2h/Screenshot%202016-09-16%2021.56.18.png?dl=1)

It's not the end of the world that the bar is wider than it should be, but it's difficult to see when it's stuck to the role. The `xshift` (which probably should have been a `yshift`, ref comment above) doesn't have any effect, unfortunately.

**Comment by camilstaps** [comment]
@nicolaiskogheim

That `xshift` doesn't work on uniqueness bars is normal, it never works on paths. See e.g.:

``` tex
\begin{tikzpicture}
    \node[rectangle,draw,minimum size=1cm] (r) {};
    \draw[draw=red,xshift=1cm] (r.south east) -- (r.north west);
\end{tikzpicture}
```

I was referring to `xshift` on the roles themselves.

If you're okay with hardcoding positioning, a workaround could be the following:

``` tex
\newdimen\bardistance
\bardistance=1.5pt
\vbinary (d) {};
\draw[uniqueness bar] ($(d.south east)+(\bardistance,0)$) -- ($(d.three south)+(\bardistance,0)$);
```

This uses the TikZ library `calc` which is automatically included when you use `tkz-orm`. You can adapt the zeros to fix the bar length.

To solve this generically, it is not enough to add some space here and there. For vroles, PGF's internal transformation matrix is changed, so we need to get the current transformation matrix and do some calculations on it (like in https://github.com/nichtich/tkz-orm/commit/d2e83c9471ec5d23d6024404c351453b33d58e80#diff-e4f76844090983f932c6df4393ddc384R1026).

**Comment by nicolaiskogheim** [comment]
> If you're okay with hardcoding positioning, a workaround could be the following:

Thank you for your swift reply. It worked like a charm!

![Screenshot of vrole with correctly placed uniqueness bar](https://www.dropbox.com/s/czh4c1h1525ghnj/Screenshot%202016-09-16%2023.57.39.png?dl=1)

``` tex
    \vbinary (d) {} ;

    \newdimen\bardistance
    \bardistance=1.5pt
    \draw[uniqueness bar]
        ($(d.south east)+(\bardistance,-1.2pt)$)
        -- ($(d.three south)+(\bardistance,.8pt)$);

```

**Comment by camilstaps** [comment]
Happy to help. If you need to get it exactly the same as for horizontal roles, have a look at the dimension definitions:

https://github.com/nichtich/tkz-orm/blob/master/tkz-orm.sty#L677

**Comment by camilstaps** [comment]
Closing because I don't use this anymore and I'm cleaning up my GitHub issues. If you want to keep this tracked, please open a new issue.
